[package]
edition = '2021'
name = "gearbox-maintenance"
version = "0.0.2-dev"
authors = ["Andreas Fuchs <asf@boinkor.net>"]
license = "MIT"
repository = "https://github.com/antifuchs/gearbox-maintenance"
readme = "README.md"
description = "A maintenance + old-data deletion tool for Transmission"
documentation = "https://docs.rs/gearbox-maintenance"

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
transmission-rpc = { git = "git://github.com/antifuchs/transmission-rpc/", branch = "done-date"}
tokio = { version = "1.14.0", features = ["full"] }
env_logger = "0.9.0"
log = "0.4.0"
anyhow = "1.0.51"
chrono = "0.4.19"
url = "2.2.2"
enum-iterator = "0.7.0"
starlark = "0.6.0"
gazebo = "0.4.4"
structopt = "0.3"
parse_duration = "2.1.1"
enum-kinds = "0.5.1"

[dev-dependencies]
test-case = "1.2.1"
