[package]
edition = '2021'
name = "gearbox-maintenance"
version = "0.0.2-dev"
authors = ["Andreas Fuchs <asf@boinkor.net>"]
license = "MIT"
repository = "https://github.com/antifuchs/gearbox-maintenance"
readme = "README.md"
description = "A maintenance + old-data deletion tool for Transmission"
documentation = "https://docs.rs/gearbox-maintenance"

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
transmission-rpc = "0.3.6"
tokio = { version = "1.16.1", features = ["full"] }
tracing = "0.1.32"
tracing-subscriber = { version = "0.3.10", features = ["env-filter"] }
anyhow = "1.0.56"
chrono = "0.4.19"
url = "2.2.2"
enum-iterator = "0.7.0"
starlark = "0.7.1"
gazebo = "0.4.4"
structopt = "0.3"
parse_duration = "2.1.1"
enum-kinds = "0.5.1"
prometheus = "0.13.0"
prometheus-hyper = "0.1"
futures = "0.3.21"
once_cell = "1.9.0"
hhmmss = "0.1.0"

[dev-dependencies]
test-case = "2.0.0"
test-log = { version = "0.2.8", features = ["trace"], default-features = false }
